name: cfm
description: A new Flutter project.


environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^2.0.2
  image_picker: ^0.5.0+3
  firebase_storage: ^2.1.0+1
  date_format: ^1.0.6
  carousel_pro: ^0.0.13


 

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/alucard.jpg
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf